server:
  port: 8087
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23liY0zxdkOXq52N5n
            clientSecret: e7edefb7b662fb7d06ef58c8041dd2217e0017a6

  datasource:
    url: jdbc:postgresql://localhost:5432/ckb_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    enabled: true
    prefix:  classpath:/templates/
    suffix: .html
    cache: false  # Disable caching for development, you can set it to true in production
#logging:
 # level:
  #  org.thymeleaf: DEBUG


